# Generated by Django 4.0.3 on 2022-05-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='assigned_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to='proj_app.myusermodel'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='assigned_ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proj_app.myusermodel'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
