# Generated by Django 4.0.3 on 2022-05-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('role', models.IntegerField()),
            ],
        ),
    ]
